# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
# IP: The module: 'design_1_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/bd_6f02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_0/bd_6f02_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/bd_6f02_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/bd_6f02_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/bd_6f02_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_12/bd_6f02_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_s00a2s_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_sarn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_srn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_sawn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_swn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_sbn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_m00s2a_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
# IP: The module: 'design_1_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/bd_6f02.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_0/bd_6f02_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/bd_6f02_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/bd_6f02_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/bd_6f02_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_12/bd_6f02_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_s00a2s_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_sarn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/bd_6f02_srn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/bd_6f02_sawn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/bd_6f02_swn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_sbn_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_m00s2a_0_ooc.xdc

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/dot_matrix_pynqZ2_vivado/dot_matrix_pynqZ2_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
