# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mul_matrix_0_10/design_1_mul_matrix_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mul_matrix_0_10 || ORIG_REF_NAME==design_1_mul_matrix_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_10/design_1_processing_system7_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_10 || ORIG_REF_NAME==design_1_processing_system7_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_10/design_1_ps7_0_axi_periph_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_10 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_7/design_1_rst_ps7_0_100M_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_7 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_8/design_1_axi_smc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_8 || ORIG_REF_NAME==design_1_axi_smc_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
