# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/mul_pynqZ2_module/mul_pynqZ2_module.srcs/sources_1/bd/design_1/ip/design_1_mul_matrix_0_10/design_1_mul_matrix_0_10.xci
# IP: The module: 'design_1_mul_matrix_0_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/mul_pynqZ2_module/mul_pynqZ2_module.srcs/sources_1/bd/design_1/ip/design_1_mul_matrix_0_10/constraints/mul_matrix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mul_matrix_0_10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/mul_pynqZ2_module/mul_pynqZ2_module.srcs/sources_1/bd/design_1/ip/design_1_mul_matrix_0_10/design_1_mul_matrix_0_10.xci
# IP: The module: 'design_1_mul_matrix_0_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/mklab/TerabyteHD/HOME_MKL/WORK/internal/mul_pynqZ2_module/mul_pynqZ2_module.srcs/sources_1/bd/design_1/ip/design_1_mul_matrix_0_10/constraints/mul_matrix_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mul_matrix_0_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
